#!/usr/bin/env python3

import os
import sys
import time
import subprocess
import RPi.GPIO as GPIO

def button_callback(channel):
    subprocess.call(["bash", "/opt/github/DSMPi/launcher_link.sh"])

def kickit():
    gpio_pin = 13
    GPIO.setwarnings(False)
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(gpio_pin, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
    GPIO.add_event_detect(gpio_pin,GPIO.RISING,callback=button_callback)

if __name__ == '__main__':
    while True:
         kickit()
         continue
