#!/usr/bin/env python3

import os
import sys
import time
import subprocess
import RPi.GPIO as GPIO

def button_callback(channel):
    subprocess.call(["bash", "/opt/github/DSMPi/launcher_link.sh"])

gpio_pin = 13

try:
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(gpio_pin, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
    while True:
       if not 'event' in locals():
          event = GPIO.add_event_detect(gpio_pin,GPIO.RISING,callback=button_callback)
          continue
       else:
          time.sleep(1)
finally:
    GPIO.cleanup()
